import { useCallback, useEffect, useMemo, useState } from "react";
import { getDashboardPrinters,getDashboardSummary,getOperationalAlerts,getOrganizationUnits } from "../services/api";
import type { DashboardPrinter,DashboardSummary,OperationalAlert,OrganizationUnit } from "../services/api";
import { parseApiDate } from "../utils/dateTime";
import "./Dashboard.css";import "./DashboardSap.css";
const DASHBOARD_REFRESH_MS=5*60*1000;
type DashboardProps={companyName:string;onManageCompany?:()=>void;onOpenPrinters:()=>void};
const EMPTY_SUMMARY:DashboardSummary={total_printers:0,active_printers:0,inactive_printers:0,online:0,offline:0,unknown:0,alerts:0,total_pages:0,page_count_known:0,page_count_unknown:0,health_average:100,manufacturers:{},generated_at:"",agent:{online:false,stale:false,communication_state:"never_seen",age_seconds:null,status:null,name:null,version:null,last_seen:null,last_error:null}};
function formatNumber(v:number){return new Intl.NumberFormat("pt-BR").format(v)}
function formatUpdateDate(v:string|null){if(!v)return"Aguardando dados";const d=parseApiDate(v);if(Number.isNaN(d.getTime()))return"Não informado";return new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(d)}
function displayPrinterName(p:DashboardPrinter){return p.custom_name||p.hostname||p.name||p.ip||"Impressora"}
function statusLabel(s:string){if(s==="online")return"Online";if(s==="offline")return"Offline";if(s==="inactive")return"Inativa";return"Desconhecido"}
function agentLabel(s:DashboardSummary){if(s.agent.online)return"Online";if(s.agent.stale)return"Atenção";return"Offline"}
function agentDetail(s:DashboardSummary){if(!s.agent.last_seen)return"sem comunicação";const x=s.agent.age_seconds;if(x===null)return formatUpdateDate(s.agent.last_seen);if(x<60)return"agora";if(x<3600)return`há ${Math.max(1,Math.floor(x/60))} min`;return`há ${Math.floor(x/3600)} h`}
function isLabelPrinter(p:DashboardPrinter){const text=`${p.manufacturer||""} ${p.model||""} ${p.name||""} ${p.hostname||""}`.toLowerCase();return text.includes("zebra")||text.includes("zt230")||text.includes("zpl")}
export default function Dashboard({companyName,onManageCompany,onOpenPrinters}:DashboardProps){
 const[summary,setSummary]=useState<DashboardSummary>(EMPTY_SUMMARY),[printers,setPrinters]=useState<DashboardPrinter[]>([]),[alerts,setAlerts]=useState<OperationalAlert[]>([]),[organizationUnits,setOrganizationUnits]=useState<OrganizationUnit[]>([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState<string|null>(null);
 const loadDashboard=useCallback(async(manual=false)=>{if(manual)setRefreshing(true);try{const[s,p,a,u]=await Promise.all([getDashboardSummary(),getDashboardPrinters(),getOperationalAlerts("all"),getOrganizationUnits()]);setSummary(s);setPrinters(p);setAlerts(a);setOrganizationUnits(u);setError(null)}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar a Visão Geral.")}finally{setLoading(false);setRefreshing(false)}},[]);
 useEffect(()=>{void loadDashboard();const id=window.setInterval(()=>void loadDashboard(),DASHBOARD_REFRESH_MS);return()=>window.clearInterval(id)},[loadDashboard]);
 const openAlerts=useMemo(()=>alerts.filter(a=>a.status==="open"),[alerts]);const topPrinters=useMemo(()=>[...printers].filter(p=>p.active&&p.page_count!==null).sort((a,b)=>Number(b.page_count||0)-Number(a.page_count||0)).slice(0,5),[printers]);
 const unitDistribution=useMemo(()=>{const c=new Map<string,number>();printers.filter(p=>p.active).forEach(p=>{const u=p.unit_name||"Sem unidade";c.set(u,(c.get(u)||0)+1)});return[...c.entries()].map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count).slice(0,5)},[printers]);
 const manufacturerDistribution=useMemo(()=>{const e=Object.entries(summary.manufacturers).sort((a,b)=>b[1]-a[1]).slice(0,5),max=Math.max(1,...e.map(([,v])=>v));return e.map(([name,value])=>({name,value,width:value/max*100,share:summary.active_printers?Math.round(value/summary.active_printers*100):0}))},[summary.manufacturers,summary.active_printers]);
 const activePrinters=useMemo(()=>printers.filter(p=>p.active),[printers]);const pageApplicablePrinters=useMemo(()=>activePrinters.filter(p=>!isLabelPrinter(p)),[activePrinters]);const pageKnownApplicable=useMemo(()=>pageApplicablePrinters.filter(p=>p.page_count!==null).length,[pageApplicablePrinters]);const labelPrinterCount=activePrinters.length-pageApplicablePrinters.length;
 const onlinePercent=summary.active_printers?Math.round(summary.online/summary.active_printers*100):0,knownPercent=pageApplicablePrinters.length?Math.round(pageKnownApplicable/pageApplicablePrinters.length*100):0,lastUpdate=summary.agent.last_seen || summary.generated_at;const hasMonitoringData=summary.total_printers>0||printers.length>0||Boolean(summary.agent.last_seen);
 function openPrinterForEditing(p:DashboardPrinter){const t=String(p.uuid||p.id||p.ip||"");if(t)sessionStorage.setItem("printflow_focus_printer",t);onOpenPrinters()}
 return <section className="sap-dashboard-page sap-dashboard-v0993">
  <div className="sap-page-head"><div><div className="sap-breadcrumb">Home <span>/</span> Visão Geral</div><h1>Visão Geral</h1><p>Acompanhe em tempo real o desempenho do parque de impressão.</p></div><div className="sap-page-actions"><button type="button" className="sap-company-chip" onClick={onManageCompany}><span>Empresa</span><strong>{companyName}</strong></button><button type="button" className="sap-refresh" disabled={refreshing} onClick={()=>void loadDashboard(true)}>{refreshing?"Atualizando...":"↻ Atualizar dados"}</button><small>Última atualização: {formatUpdateDate(lastUpdate)}</small></div></div>
  {error&&<div className="sap-message-error"><strong>Não foi possível atualizar os dados.</strong><span>{error}</span></div>}{loading&&<div className="sap-loading">Atualizando indicadores...</div>}{!loading&&!error&&!hasMonitoringData&&<div className="sap-empty"><strong>Aguardando dados</strong><span>Monitoramento ainda não iniciado.</span><small>Instale e conecte o Agent para começar.</small></div>}
  <div className="sap-kpi-grid sap-kpi-grid-six"><article className="sap-kpi-card"><span className="sap-kpi-icon">▤</span><div><small>Total de páginas</small><strong>{formatNumber(summary.total_pages)}</strong><em>contadores monitorados</em></div></article><article className="sap-kpi-card"><span className="sap-kpi-icon green">▣</span><div><small>Impressoras ativas</small><strong>{summary.active_printers}</strong><em>{onlinePercent}% online</em></div></article><article className="sap-kpi-card"><span className="sap-kpi-icon">▦</span><div><small>Unidades</small><strong>{organizationUnits.length}</strong><em>cadastradas</em></div></article><article className="sap-kpi-card"><span className="sap-kpi-icon">◎</span><div><small>Contadores válidos</small><strong>{pageKnownApplicable}/{pageApplicablePrinters.length}</strong><em>{knownPercent}% dos aplicáveis{labelPrinterCount?` • ${labelPrinterCount} etiqueta(s) N/A`:""}</em></div></article><article className="sap-kpi-card"><span className="sap-kpi-icon red">△</span><div><small>Alertas</small><strong>{openAlerts.length}</strong><em>{openAlerts.length?"requerem atenção":"Tudo normal"}</em></div></article><article className={`sap-kpi-card sap-agent-kpi ${summary.agent.online?"is-online":""}`}><span className="sap-kpi-icon green">◉</span><div><small>Agent</small><strong>{agentLabel(summary)}</strong><em>Última comunicação: {agentDetail(summary)}</em><em>{summary.agent.version?`v${summary.agent.version} • Windows`:summary.agent.name||"PRINTFLOW Agent"}</em></div></article></div>
  <div className="sap-dashboard-grid sap-dashboard-grid-overview"><article className="sap-panel"><header><div><span>PARQUE DE IMPRESSÃO</span><h2>Distribuição por fabricante</h2></div></header><div className="sap-bars">{manufacturerDistribution.length?manufacturerDistribution.map(i=><div className="sap-bar-row sap-bar-with-share" key={i.name}><span>{i.name||"Desconhecido"}</span><div><i style={{width:`${i.width}%`}}/></div><strong>{i.value}</strong><em>{i.share}%</em></div>):<p className="sap-empty">Sem dados de fabricantes.</p>}</div></article><article className="sap-panel"><header><div><span>STATUS</span><h2>Status das impressoras</h2></div></header><div className="sap-donut-wrap"><div className="sap-donut" style={{"--online":`${onlinePercent*3.6}deg`} as React.CSSProperties}><div><strong>{summary.active_printers}</strong><span>total</span></div></div><div className="sap-status-list"><span><i className="online"/>Online <strong>{summary.online} · {onlinePercent}%</strong></span><span><i className="offline"/>Offline <strong>{summary.offline}</strong></span><span><i className="unknown"/>Desconhecido <strong>{summary.unknown}</strong></span></div></div></article><article className="sap-panel"><header><div><span>ORGANIZAÇÃO</span><h2>Equipamentos por unidade</h2></div></header><div className="sap-unit-list">{unitDistribution.map(u=><div key={u.name}><span>{u.name}</span><div><i style={{width:`${Math.max(8,u.count/Math.max(1,summary.active_printers)*100)}%`}}/></div><strong>{u.count}</strong></div>)}</div></article></div>
  <article className="sap-panel sap-printer-ranking"><header><div><span>UTILIZAÇÃO</span><h2>Impressoras com maior contador</h2></div><button type="button" onClick={onOpenPrinters}>Ver todas</button></header><div className="sap-table-wrap"><table className="sap-table"><thead><tr><th>#</th><th>Impressora</th><th>Modelo</th><th>IP</th><th>Setor</th><th>Páginas</th><th>Status</th></tr></thead><tbody>{topPrinters.map((p,index)=><tr key={p.uuid||p.id||index} role="button" tabIndex={0} onClick={()=>openPrinterForEditing(p)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openPrinterForEditing(p)}}}><td>{index+1}</td><td><strong>{displayPrinterName(p)}</strong></td><td>{p.model||p.manufacturer||"-"}</td><td>{p.ip||"-"}</td><td>{p.sector_name||"Não definido"}</td><td><strong>{formatNumber(Number(p.page_count||0))}</strong></td><td><span className={`sap-status-dot ${p.status}`}/>{statusLabel(p.status)}</td></tr>)}</tbody></table></div></article>
  <div className={`sap-health-strip ${openAlerts.length?"has-alerts":""}`}><div><span className="sap-health-icon">✓</span><p><strong>{openAlerts.length?`${openAlerts.length} alerta(s) requerem atenção`:"Parque de impressão saudável"}</strong><small>{openAlerts.length?"Consulte as impressoras para verificar as ocorrências.":"Todas as impressoras estão online e operando normalmente."}</small></p></div><button type="button" onClick={onOpenPrinters}>{openAlerts.length?"Ver alertas":"✓ Sem alertas no momento"}</button></div>
 </section>
}
